version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10  # Choose the appropriate Python version
    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest

      # Run the tests
      - run:
          name: Run tests
          command: |
            pytest -s test_app.py

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
